import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/global/navbar";

export const metadata: Metadata = {
  title: "S5SAJID — Web Dev",
  description: "Generated by S5SAJID — Web Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background dark text-foreground">
        <Navbar />
        {children}
        
      </body>
    </html>
  );
}
